name: Kivy Android Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Kivy and Build Tools
        run: |
          pip install --upgrade pip
          pip install kivy kivy-uix kivy-core kivy-app kivy-lang kivy-audio kivy-theming kivy-garden
          pip install buildozer
          sudo apt update && sudo apt install -y build-essential python3-dev libpython3-dev kivy-tools

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: bin/Release/*.apk
